# test frontend
# test backend
# deploy!

name: Test + Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm version && npm install -g npm@7 && npm version
        name: Upgrade npm
      - run: cd frontend && npm install && npm run build && cd ..
        name: Build Frontend
      - run: echo "${{ secrets.PRODUCTION_ENV }}" > .env
        name: Paste production environment variables into .env for gcloud
      - name: Deploy to Google App Engine
        uses: atRobertoFlores/gae_deploy_action@master
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_name: ${{ secrets.GCP_PROJECT_NAME }}
